# Generated by Django 4.0.3 on 2022-08-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_alter_productinstance_options_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Price for 1 bag', max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='quantity',
            field=models.IntegerField(help_text='Enter number of bags'),
        ),
    ]
