# Generated by Django 4.0.3 on 2022-08-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_remove_product_price_productinstance_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstance',
            old_name='price',
            new_name='unit_price',
        ),
    ]
